version: '3.7'

services:
  chatbot:
    env_file:
      - chatbot.env
    image: chatbot:latest
#    command: 'bash -c "sleep 100000"'
    command: 'bash -c "/home/botuser/env/bin/python src/audio_manager.py"'
    # TODO: only for debugging, delete when in production
    volumes:
      - ./src:/app
#    build:
#      src
    ports:
      - "5000:5000"
    depends_on:
      - tts
    networks:
      - chatbot

  tts:
    image: synesthesiam/mozillatts
    ports:
      - "5002:5002"
    networks:
      - chatbot

networks:
  chatbot:
