version: '3'

services:
  chatbot:
    env_file:
      - chatbot.env
    build: ./chatbot/
    command: python3 -m poetry run python chatbot/bot.py
    volumes:
      - ./chatbot:/app/chatbot
    ports:
      - "5000:5000"
    networks:
      - chatbot

  netdata:
    image: netdata/netdata
    ports:
      - 19999:19999
    environment:
      - DOCKER_HOST=proxy:2376
      - DO_NOT_TRACK=1
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    restart: always
    networks:
      - chatbot
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  proxy:
    restart: always
    image: nginx:alpine
    ports:
      - 80:80/tcp
      - 443:443/tcp
    depends_on:
      - chatbot
      - netdata
    secrets:
      -   source: proxy.ca
          target: /etc/nginx/certs/rengine_chain.pem
      -   source: proxy.cert
          target: /etc/nginx/certs/rengine.pem
      -   source: proxy.key
          target: /etc/nginx/certs/rengine_rsa.key
    volumes:
      - ./config/nginx/chatbot.conf:/etc/nginx/conf.d/chatbot.conf:ro
    networks:
      - chatbot

networks:
  chatbot:

secrets:
  proxy.ca:
    file: ./secrets/certs/rengine_chain.pem
  proxy.key:
    file: ./secrets/certs/rengine_rsa.key
  proxy.cert:
    file: ./secrets/certs/rengine.pem