version: '3'

services:
  chatbot:
    env_file:
      - chatbot.env
    build: ./chatbot/
    command: python3 -m poetry run python chatbot/bot.py
    volumes:
      - ./chatbot:/app/chatbot
    ports:
      - "5000:5000"
    networks:
      - chatbot

networks:
  chatbot:
