[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = "Simple Chatbot"
authors = ["amit-bakhru <bakhru@me.com>"]

[tool.poetry.dependencies]
python = "^3.7"
nltk = "^3.4.5"
wikipedia = "^1.4.0"
sklearn = "^0.0"
google = "^2.0.2"
colorlog = "^4.0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
