[tool.poetry]
name = "chatbot"
version = "0.1.0"
description = ""
authors = ["amit-bakhru <amit@area1security.com>"]

[tool.poetry.dependencies]
python = "^3.7"
nltk = "^3.4.5"
wikipedia = "^1.4.0"
sklearn = "^0.0"
google-search-results = "^1.7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
